crm/urls.py
from django.urls import path
from .views import *

app_name='crm'


urlpatterns = [
        path('home/',home,name="home_show"),
        path('products/',products,name="products_show"),
        path('customers/',customers,name="customers_show"),
]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('crm.urls',namespace='crm')),
]

crm/models.py
from django.db import models

# Create your models here.

crm/views.py
from django.shortcuts import render

def home(request):
    return render(request,'crm/dashbord.html')

def products(request):
    return render(request,'crm/products.html')

def customers(request):
    return render(request,'crm/customer.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    {%  block title %} {% endblock %}
    <style>

    </style>
</head>
<body>
{% include 'html_template/nav.html' %}

{% block content %}

{% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">

</script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">

</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">

</script>
</html>

templates/crm/customer.html
{% extends 'base.html' %}



{% block  title %}

{% endblock %}




{% block  content %}

<div class="row mb-2">
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Клиент</h5>
                <hr>
                <a class="btn btn-outline-info btn-block mb-2" href="#" >Обновить информацию о клиентах</a>
                <a class="btn btn-outline-danger btn-block mb-2" href="#">Удалить клиента</a>
            </div>
        </div>
    </div>

    <div class="col-md-4 mb-2">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Контактная информация</h5>
                <hr>
                <p>Электронная почта:</p>
                <p>Телефон:</p>
            </div>
        </div>
    </div>

    <div class="col-md-4 mb-2">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Общее количество заказов</h5>
                <hr>
                <h1 class="text-center" style="padding: 10px;"></h1>
            </div>
        </div>
    </div>
</div>

<div class="row mb-2">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="get">
                    <button class="btn btn-primary" type="submit">Поиск</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row mb-2">
    <div class="col-md">
        <div class="card">
            <div class="card-body">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th>Продукт</th>
                            <th>Категория</th>
                            <th>По дате</th>
                            <th>Статус</th>
                            <th>Обновление</th>
                            <th>Удалить</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>



{% endblock %}

templates/crm/dashbord.html
{% extends 'base.html' %}



{% block  title %}

{% endblock %}




{% block  content %}

    {% include 'crm/status.html' %}

<div class="row">
    <div class="col-md-5">
        <h5>CUSTOMERS:</h5>
        <hr>
        <div class="card card-body">
            <a class="btn btn-primary btn-sm btn-block" href="">
                Create Customers
            </a>
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>Customers</th>
                    <th>Orders</th>
                </tr>
            </table>
        </div>
    </div>

<div class="col-md-5">
    <h5>LAST 5 ORDERS</h5>
    <hr>
    <div class="card card-body">
        <a class="btn btn-primary btn-sm btn-block">
            Create Order
        </a>
        <table class="table table-sm">
            <tr>
                <th>Product</th>
                <th>Date Orderd</th>
                <th>Status</th>
                <th>Update</th>
                <th>Remove</th>
            </tr>
        </table>
    </div>
</div>

</div>




{% endblock %}

templates/crm/products.html
{% extends 'base.html' %}



{% block  title %}

{% endblock %}




{% block  content %}
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Products</h5>
        </div>
        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Price</th>
                </tr>
            </table>
        </div>
    </div>
</div>


{% endblock %}

templates/crm/status.html
<br>
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3" id="total-orders">
                <div class="card-header">
                    <h5 class="card-title">Total Orders</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title"></h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3" id="orders-delivered">
                <div class="card-header">
                    <h5 class="card-title">
                        Orders Delivered
                    </h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">
                    </h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3" id="orders-pending">
              <div class="card-header">
                  <h5 class="card-title">
                      Orders Pending
                  </h5>
              </div>
                <div class="card-body">
                    <h3 class="card-title">

                    </h3>
                </div>
            </div>
        </div>
    </div>
</br>

templates/html_template/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'crm:home_show' %}">Dashbord</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'crm:products_show' %}">Products</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'crm:customers_show' %}">Customers</a>
      </li>
    </ul>
  </div>
</nav>